pull_request.md
Create a PR template
* This is to ensure pull requests are following the agreed approach in the team especially providing a What and Why to their PRs
* This is to ensure the devs are doing basic fundamental things in before submitting a PR, e.g. reviewing their own PR for things like linting.  This saves a lot of time for the reviewer
=> TLF-153 Create pull_request template

apps/ecs/fields/index.js, apps/ecs/index.js, apps/ecs/sections/summary-data-sections.js, apps/ecs/translations/src/en/fields.json, apps/ecs/translations/src/en/pages.json, apps/ecs/translations/src/en/validation.json, apps/ecs/views/check-requested.html, apps/ecs/views/content/en/request-check-before-1988.md, apps/ecs/views/request-check-before-1988.html, apps/ecs/views/settlement-protection.html, assets/scss/app.scss
TLF-184 - ECS - Does the worker have an ongoing appeal or application with the Home Office? pages [TLF-184](https://collaboration.homeoffice.gov.uk/jira/browse/TLF-184)
- Added new pages for does the worker has ongoing appeal and continuous pages in ECS flow
- Added required field validation for all pages
- added necessary step configuration and field specific variables.
=> TLF-184 Added ongoing appeal and continuous pages

apps/ecs/fields/index.js, apps/ecs/index.js, apps/ecs/sections/summary-data-sections.js, apps/ecs/translations/src/en/fields.json, apps/ecs/translations/src/en/pages.json, apps/ecs/translations/src/en/validation.json, apps/ecs/views/ineligible-document.html
Relates [TLF-186](https://collaboration.homeoffice.gov.uk/jira/browse/TLF-186)
What
* Added form flow for original document
=> TLF-186-seen-original-document

apps/ecs/fields/index.js, apps/ecs/index.js, apps/ecs/sections/summary-data-sections.js, apps/ecs/translations/src/en/fields.json, apps/ecs/translations/src/en/pages.json, apps/ecs/translations/src/en/validation.json
Relates [TLF-188](https://collaboration.homeoffice.gov.uk/jira/browse/TLF-188)
What
* Added worker job form flow and business address page
=> TLF-188 worker job info

apps/ecs/behaviours/check-validation.js, apps/ecs/fields/index.js, apps/ecs/index.js, apps/ecs/sections/summary-data-sections.js, apps/ecs/translations/src/en/fields.json, apps/ecs/translations/src/en/pages.json, apps/ecs/translations/src/en/validation.json, assets/js/index.js, assets/scss/app.scss, package.json, yarn.lock
TLF-187 - ECS - Worker's current situation pages [TLF-187](https://collaboration.homeoffice.gov.uk/jira/browse/TLF-187)
- Added new pages for Worker's current situation in ECS flow
- Added required field validation for all pages
- National Insurance Number validation rules taken from DWP repo 
- For reference: detailed information on regex can be found on 
[DWP’s NINO validator git repo](https://github.com/dwp/nino-format-validation)
- added necessary step configuration and field specific variables.
=> TLF-187 - Worker's current situation pages 

apps/ecs/fields/index.js, apps/ecs/index.js, apps/ecs/translations/src/en/buttons.json, apps/ecs/translations/src/en/fields.json, apps/ecs/translations/src/en/pages.json, apps/ecs/translations/src/en/validation.json, apps/ecs/views/check-requested.html, apps/ecs/views/content/en/data-protection-statement.md, apps/ecs/views/content/en/privacy-policy.md, apps/ecs/views/data-protection.html, assets/js/index.js, assets/scss/app.scss
Relates [TLF-192](https://collaboration.homeoffice.gov.uk/jira/browse/TLF-192)
What
* Add data protection statement page
=> TLF-192-add data protection statement

apps/ecs/behaviours/check-validation.js, apps/ecs/fields/index.js, apps/ecs/index.js, apps/ecs/sections/summary-data-sections.js, apps/ecs/translations/src/en/fields.json, apps/ecs/translations/src/en/pages.json, apps/ecs/translations/src/en/validation.json
Relates [TLF-284](https://collaboration.homeoffice.gov.uk/jira/browse/TLF-284)
What
Change form flow according to changes in figma.
Changes to validation messages for worker-details pages will be completed as part of [TLF-285](https://collaboration.homeoffice.gov.uk/jira/browse/TLF-285)
=> TLF-284-change-flow

apps/ecs/fields/index.js, apps/ecs/index.js, apps/ecs/sections/summary-data-sections.js, apps/ecs/translations/src/en/fields.json, apps/ecs/translations/src/en/pages.json, apps/ecs/translations/src/en/validation.json, apps/ecs/views/partials/summary-table.html, assets/scss/app.scss, package.json, yarn.lock
TLF-191 - ECS - Summary page - [TLF-191](https://collaboration.homeoffice.gov.uk/jira/browse/TLF-191)
- checking all fields in summary page populating correctly if we change any dependant fields from change link on summary screen
- added some condition to populate all fields correctly
=> TLF-191 - ECS - Added some extra conditions to populate the answers in check answers 

.drone.yml, bin/deploy.sh, kube/app/ingress-external.yml, kube/app/ingress-internal.yml
What:
The project need a staging environment
Why:
To carry out performance testing 
How:
Adding conditionals to the deployment yaml files to handle the staging namespace
=> TLF-292: add the staging environment to the ECS project

apps/ecs/behaviours/check-validation.js, apps/ecs/fields/index.js, apps/ecs/translations/src/en/fields.json, apps/ecs/translations/src/en/validation.json
Relates [TLF-285](https://collaboration.homeoffice.gov.uk/jira/browse/TLF-285)
What
Add missing validation messages and logic to fields
=> TLF-285-add missing validations

.drone.yml, apps/ecs/behaviours/check-validation.js, apps/ecs/behaviours/save-session.js, apps/ecs/behaviours/send-email-notification.js, apps/ecs/fields/index.js, apps/ecs/index.js, apps/ecs/sections/summary-data-sections.js, apps/ecs/translations/src/en/fields.json, apps/ecs/translations/src/en/validation.json
TLF-293 - ECS - Additional validation message - 
[TLF-293](https://collaboration.homeoffice.gov.uk/jira/browse/TLF-293)
[TLF-294](https://collaboration.homeoffice.gov.uk/jira/browse/TLF-294)
- checking all fields validations in all pages with the figma and the spreadsheet
- added some changes in validation messages and validation rules
=> TLF-293 - ECS - Added additional validation messages

.devcontainer/Dockerfile, .drone.yml, Dockerfile, apps/ecs/behaviours/send-email-notification.js, package.json, yarn.lock
[TLF-289](https://collaboration.homeoffice.gov.uk/jira/browse/TLF-289) - ECS - Upgrade Node and dependency packages
upgrade to node:20.16.0-alpine3.20
upgrade to hof@21.0.3
=> TLF-289 - ECS - Upgrade Node and dependency packages

.drone.yml
**What**
In .drone.yml update node image and update cron jobs and slack steps as per final version of COA
**How**
Amending the pipeline steps in .drone.yml 
**Why**
Snyk was removed but the scan image was pending of final approval until used.
=> HOFF-314: add scan image drone step and amend cron jobs and slack

README.md
Adds minor change to README to prompt a new branch build including recently added GA tags in configmap.
=> TLF-268 Update README to test GA integration

.devcontainer/Dockerfile, .drone.yml, Dockerfile, package.json, yarn.lock
[TLF-327](https://collaboration.homeoffice.gov.uk/jira/browse/TLF-327) ECS - Upgrade Node and dependency packages
- Node.js 20.17.0 ( Alpine 3.20 )
- hof 21.1.1
- notifications-node-client 8.2.1
=> TLF-327 - ECS - Upgrade Node and dependency packages

README.md, apps/ecs/index.js, apps/ecs/translations/src/en/pages.json, apps/ecs/views/content/en/accessibility.md, apps/ecs/views/static/accessibility.html, hof.settings.json
Accessibility statement update
[TLF-334](https://collaboration.homeoffice.gov.uk/jira/browse/TLF-334)
Once the accessibility testing is concluded and we know the output, we need to ensure the accessibility statement is updated for the Employer's checking service form
=> TLF-334 - ECS - Accessibility statement update

apps/ecs/translations/src/en/fields.json, apps/ecs/views/content/en/data-protection-statement.md, apps/ecs/views/content/en/privacy-policy.md, apps/ecs/views/content/en/request-check-before-1988.md, apps/ecs/views/content/en/right-to-work-check.md
## What?
- [TLF-362](https://collaboration.homeoffice.gov.uk/jira/browse/TLF-362)
- Content changes - Request-check, Request-check-before-1988, data-protection
- Content changes for:
/request-check
/request-check-before-1988
/data-protection
- updated the content in corresponding md file.
=> TLF-362 - ECS - content changes - updated for three pages

apps/ecs/index.js
Relates [ECS-72](https://collaboration.homeoffice.gov.uk/jira/browse/ECS-72)
What
Changes flow so /worker-details goes to /reference-number
=> ECS-72-HO-ref-number-for-all-workers

config.js, pull_request_template.md, server.js, yarn.lock
- updated service so automatically pulls correct feedback URL for each environment
- added pull request template
https://collaboration.homeoffice.gov.uk/jira/browse/ECS-68
- updated feedbackUrl property (config.js)
- updated reference to feedbackUrl (server.js)
- upgraded packages (yarn.lock)
- added pull request template (pull_request_template.md)
here is an [example commit](https://github.com/UKHomeOfficeForms/hof/commit/810959f391187c7c4af6db262bcd143b50093a6e)
=> ECS-68: Update Feedback Form

apps/ecs/views/content/en/privacy-policy.md, apps/ecs/views/content/en/right-to-work-check.md
Updated content for /request-check and /data-protection pages.
As per Business requirements, please see following ticket [ECS 65](https://collaboration.homeoffice.gov.uk/jira/browse/ECS-65)
Modified the Markdown files for the the request-check and data-protection pages.
Manually went through the form to check correct contents. 
here is an [example commit](https://github.com/UKHomeOfficeForms/hof/commit/810959f391187c7c4af6db262bcd143b50093a6e)
=> [ECS 65] updated content for /request check and /data-protection pages. 

apps/ecs/views/content/en/accessibility.md
Updated Accessibility statement to note that it is fully compliant with WCAG 2.2 AA
https://collaboration.homeoffice.gov.uk/jira/browse/BRP-151
updated accessibility.md 
here is an [example commit](https://github.com/UKHomeOfficeForms/hof/commit/810959f391187c7c4af6db262bcd143b50093a6e)
=> ECS-86: Update accessibility statement

package.json, yarn.lock
[ECS-92](https://collaboration.homeoffice.gov.uk/jira/browse/ECS-92) - Update HOF to latest version
Tested on local machine 
here is an [example commit](https://github.com/UKHomeOfficeForms/hof/commit/810959f391187c7c4af6db262bcd143b50093a6e)
=> ECS-92 Update HOF to latest version
